- name: Сохранение текущей конфигурации на ASA устройствах
  hosts: asa
  gather_facts: no
  tasks:
    - name: Сохранить текущую конфигурацию
      cisco.asa.asa_config:
        commands:
          - sh rou
      register: save_result

    - name: Вывести результат сохранения
      debug:
        var: save_result
